server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mdsagir/spring-config-store
          search-paths:
            - '*service'
          #username: in case of private repository
          #password:
